name: C/C++ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y install gcc

    - name: Build ctr_firm_builder
      uses: actions/checkout@v3
      with:
        repository: derrekr/ctr_firm_builder
        path: ctr_firm_builder
      run: |
        cd ctr_firm_builder
        make

    - name: Build project
      run: |
        export PATH=$PWD/ctr_firm_builder:$PATH
        make nightly
        echo ${{ github.sha }} >> ./nightly/nightly_commit.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: open_agb_firm_nightly
        path: ./nightly
        if-no-files-found: error
